version: '3.3'

services:
  bkapi:
    image: bk-api:latest
    restart: always
    env_file: .env.docker
    ports:
      - 3000:3000
    volumes:
      - ./data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
